# Generated by Django 4.0 on 2021-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hq', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
            ],
        ),
    ]
