# Generated by Django 4.0 on 2021-12-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='descricao1',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='descricao2',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='descricao3',
        ),
    ]
